### ISSUE TITLE
Bot Functionality Idea

### ISSUE THREAD

**Issue by TheGreatCookieMachine** [jonasbohmann/democraciv-discord-bot#8]
I have noticed that sometimes people will reference parties by acronyms (ie MPN instead of Monarchist Party of Norway) or forget spaces (ie Cloud9 instead of Cloud 9). My idea is that we introduce 3 new commands:

1. `-addpartyalias`: Creates a new party alias
2. `-removepartyalias`: Removes a party alias
3. `-listpartyalias`: Lists a parties name and all aliases

The first two commands would be referenced like so `-<command name> <party name>, <alias>` with the first simply having the party name or a related alias. For the sake of simplicity we can also make the capwordParties aliases which are automatically defined upon creating a party.

These aliases would be used as alternatives to actual party names. For example if MPN was an alias of Monarchist Party of Norway, `-join MPN` would add the user to the Monarchist Party of Norway.

If you think the idea sounds good I can try to get started on it next week, however I am having my wisdom teeth removed tomorrow and am not sure when I will be able to start coding again. In addition to this just over a week after I am traveling without a computer. If I am not able to get it done next week I can work on it early September.

**Comment by jonasbohmann** [comment]
Sounds like a good idea! This will be especially useful if we choose to have the faction system for the next game.

If I can find some time in the next couple of days, I'll start working on it.

**Comment by TheGreatCookieMachine** [comment]
I recovered from the extraction faster than I thought so I went ahead and started experimenting on it yesterday. If you would like to take over I will delete the fork, otherwise it should be done in a day or two.
